#  ------------------------------------------------------------
#  |                     GuildHome plugin                     |
#  |                                                          |
#  |           Author : huda0209                              |
#  |           Depend :                                       |
#  |  GitHub : https://github.com/stella-server-mc/GuildHome  |
#  |                    ran by spigot 1.16                    |
#  ------------------------------------------------------------


#Enumerate block IDs that you don't want destroyed
#Be sure to write in capital letters
#If you want to check up the block id, look this page.
#https://papermc.io/javadocs/paper/1.16/org/bukkit/Material.html

BreakBlock:
  - GLASS
  - GLASS_PANE